// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZMCtdlFJ9DyAIAfz-CTrnqiHavRP9PiY',
    appId: '1:869904844487:web:74c1c04b7dcf77aa0b60e2',
    messagingSenderId: '869904844487',
    projectId: 'isrochronicle',
    authDomain: 'isrochronicle.firebaseapp.com',
    storageBucket: 'isrochronicle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXkQB9gqxddsu3HxGqKdeGo6cCmqx6uM',
    appId: '1:869904844487:android:bb128ae293d2da650b60e2',
    messagingSenderId: '869904844487',
    projectId: 'isrochronicle',
    storageBucket: 'isrochronicle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxREsD1UTUoPRqYUQKS8JHuYXGgRls3s4',
    appId: '1:869904844487:ios:70f75564480156850b60e2',
    messagingSenderId: '869904844487',
    projectId: 'isrochronicle',
    storageBucket: 'isrochronicle.appspot.com',
    iosClientId: '869904844487-12mtt7i58vhq5ke87ecqnf3d7kudt50a.apps.googleusercontent.com',
    iosBundleId: 'com.example.isroChronicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxREsD1UTUoPRqYUQKS8JHuYXGgRls3s4',
    appId: '1:869904844487:ios:bbd02cd5c823f7a50b60e2',
    messagingSenderId: '869904844487',
    projectId: 'isrochronicle',
    storageBucket: 'isrochronicle.appspot.com',
    iosClientId: '869904844487-q75dcsiqmn9ie8olj8b4v1hbihjebn13.apps.googleusercontent.com',
    iosBundleId: 'com.example.isroChronicle.RunnerTests',
  );
}
